
sectors = {
   "Basic Materials":[
      "Agricultural Inputs",
      "Building Materials",
      "Chemicals",
      "Specialty Chemicals",
      "Lumber & Wood Production",
      "Paper & Paper Products",
      "Aluminum",
      "Copper",
      "Other Industrial Metals & Mining",
      "Gold",
      "Silver",
      "Other Precious Metals & Mining",
      "Coking Coal",
      "Steel"
   ],
   "Consumer Cyclical":[
      "Auto & Truck Dealerships",
      "Auto Manufacturers",
      "Auto Parts",
      "Recreational Vehicles",
      "Furnishings, Fixtures & Appliances",
      "Residential Construction",
      "Textile Manufacturing",
      "Apparel Manufacturing",
      "Footwear & Accessories",
      "Packaging & Containers",
      "Personal Services",
      "Restaurants",
      "Apparel Retail",
      "Department Stores",
      "Home Improvement Retail",
      "Luxury Goods",
      "Internet Retail",
      "Specialty Retail",
      "Gambling",
      "Leisure",
      "Lodging",
      "Resorts & Casinos",
      "Travel Services"
   ],
   "Financial Services":[
      "Asset Management",
      "Banks—Diversified",
      "Banks—Regional",
      "Mortgage Finance",
      "Capital Markets",
      "Financial Data & Stock Exchanges",
      "Insurance—Life",
      "Insurance—Property & Casualty",
      "Insurance—Reinsurance",
      "Insurance—Specialty",
      "Insurance Brokers",
      "Insurance—Diversified",
      "Shell Companies",
      "Financial Conglomerates",
      "Credit Services"
   ],
   "Real Estate":[
      "Real Estate—Development",
      "Real Estate Services",
      "Real Estate—Diversified",
      "REIT—Healthcare Facilities",
      "REIT—Hotel & Motel",
      "REIT—Industrial",
      "REIT—Office",
      "REIT—Residential",
      "REIT—Retail",
      "REIT—Mortgage",
      "REIT—Specialty",
      "REIT—Diversified"
   ],
   "Consumer Defensive":[
      "Beverages—Brewers",
      "Beverages—Wineries & Distilleries",
      "Beverages—Non-Alcoholic",
      "Confectioners",
      "Farm Products",
      "Household & Personal Products",
      "Packaged Foods",
      "Education & Training Services",
      "Discount Stores",
      "Food Distribution",
      "Grocery Stores",
      "Tobacco"
   ],
   "Healthcare":[
      "Biotechnology",
      "Drug Manufacturers—General",
      "Drug Manufacturers—Specialty & Generic",
      "Healthcare Plans",
      "Medical Care Facilities",
      "Pharmaceutical Retailers",
      "Health Information Services",
      "Medical Devices",
      "Medical Instruments & Supplies",
      "Diagnostics & Research",
      "Medical Distribution"
   ],
   "Utilities":[
      "Utilities—Independent Power Producers",
      "Utilities—Renewable",
      "Utilities—Regulated Water",
      "Utilities—Regulated Electric",
      "Utilities—Regulated Gas",
      "Utilities—Diversified"
   ],
   "Communication Services":[
      "Telecom Services",
      "Advertising Agencies",
      "Publishing",
      "Broadcasting",
      "Entertainment",
      "Internet Content & Information",
      "Electronic Gaming & Multimedia"
   ],
   "Energy":[
      "Oil & Gas Drilling",
      "Oil & Gas E&P",
      "Oil & Gas Integrated",
      "Oil & Gas Midstream",
      "Oil & Gas Refining & Marketing",
      "Oil & Gas Equipment & Services",
      "Thermal Coal",
      "Uranium"
   ],
   "Industrials":[
      "Aerospace & Defense",
      "Specialty Business Services",
      "Consulting Services",
      "Rental & Leasing Services",
      "Security & Protection Services",
      "Staffing & Employment Services",
      "Conglomerates",
      "Engineering & Construction",
      "Infrastructure Operations",
      "Building Products & Equipment",
      "Farm & Heavy Construction Machinery",
      "Industrial Distribution",
      "Business Equipment & Supplies",
      "Specialty Industrial Machinery",
      "Metal Fabrication",
      "Pollution & Treatment Controls",
      "Tools & Accessories",
      "Electrical Equipment & Parts",
      "Airports & Air Services",
      "Airlines",
      "Railroads",
      "Marine Shipping",
      "Trucking",
      "Integrated Freight & Logistics",
      "Waste Management"
   ],
   "Technology":[
      "Information Technology Services",
      "Software—Application",
      "Software—Infrastructure",
      "Communication Equipment",
      "Computer Hardware",
      "Consumer Electronics",
      "Electronic Components",
      "Electronics & Computer Distribution",
      "Scientific & Technical Instruments",
      "Semiconductor Equipment & Materials",
      "Semiconductors",
      "Solar"
   ]
}

funds = {
    "Basic Materials":"XLB",
    "Consumer Cyclical":"XLY",
    "Financial Services":"XLF",
    "Real Estate":"XLRE",
    "Consumer Defensive":"XLP",
    "Healthcare":"XLV",
    "Utilities":"XLU",
    "Communication Services":"XLC",
    "Energy":"XLE",
    "Industrials":"XLI",
    "Technology":"XLK"
}

sectors_ticker_to_name = {
    "GDX":"Gold", 
    "XLC":"Communication Services",
    "XLY":"Consumer Cyclical",
    "XLP":"Consumer Defensive",
    "XLE":"Energy",
    "XLF":"Financial Services",
    "XLV":"Healthcare",
    "XLI":"Industrials",
    "XLB":"Basic Materials",
    "XLRE":"Real Estate",
    "XLK":"Technology",
    "XLU":"Utilities",
    "TLT":"20Y Bonds",
    "SPY":"S&P500"
}